In [1]:
## Importing numpy library

import numpy as np

In [2]:
## Creating a numpy array using list
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
## Creating a array using matrix

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
## Returns every spaced values within the given range.

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
## Generating arrays of zero and ones
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
## 

np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
## It creates a identity matrix.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
## It creates a n array in the range(0,1)
np.random.rand(5,2)

array([[0.50523239, 0.78474245],
       [0.14731869, 0.3721589 ],
       [0.32442959, 0.77212239],
       [0.42492979, 0.935039  ],
       [0.70666944, 0.74834968]])

In [14]:
## It returns samples from the standard normal distribution whose standard eviation is 1.
np.random.randn(2,3)

array([[ 0.69272866, -0.1297155 ,  1.3119494 ],
       [-0.03300727,  0.46111238,  0.18805269]])

In [15]:
##Creates an array of random integers in the given range.

np.random.randint(0,101,(5,4))

array([[36, 36, 60, 55],
       [71, 84, 68, 57],
       [ 9, 47, 27, 86],
       [70,  1, 63, 66],
       [22, 79, 86, 20]])

In [16]:
## It returns the same random integer whenever seed is used.
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [18]:

arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
## Used for Reshaping the array

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
randarr = np.random.randint(0,101,10)

In [22]:
randarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [24]:
## maximum value
randarr.max()

99

In [25]:
## minimum value
randarr.min()

2

In [26]:
## returns minimum value index
randarr.argmin()

7

In [27]:
## returns maximum value index
randarr.argmax()

5

In [28]:
# returns the datatype
randarr.dtype

dtype('int32')

In [29]:
## returns shape
arr.shape

(25,)

In [54]:
arr = arr.reshape(5,5)

In [55]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arr.shape

(5, 5)

# Indexing and Selection

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
## returns value at index 8
arr[8]

8

In [31]:
## return values from index 1 to 4 excluding 5.
arr[1:5]

array([1, 2, 3, 4])

In [32]:
## returns value from starting of the index till 4 excluding 5
arr[:5]

array([0, 1, 2, 3, 4])

In [33]:
## returns value starting from 5th index to the end.
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
## it changes the value of the array from index 0 to 4
arr[0:5] = 100

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [37]:
arr = np.arange(0,11)

In [38]:
## this method of taking a new variable does not make a change in the real array.

slice_of_arr = arr[0:5]

In [39]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_of_arr[:] = 99

In [42]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [45]:
## If we don't want to have change in the real array we have to use below steps.

arr_copy = arr.copy()

In [46]:
arr_copy[:] = 100

In [47]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [49]:
## creating 2d array
arr_2d = np.array([[5,10,15],[20,25,20],[35,40,45]])

In [50]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [80]:
arr_2d.shape

(3, 3)

In [81]:
arr_2d[0]

array([ 5, 10, 15])

In [85]:
arr_2d[1,2]

20

In [51]:
## Indexing is done on teh basis of (rows,columns)

arr_2d[:2,1:]

array([[10, 15],
       [25, 20]])

In [52]:
arr = np.arange(1,11)

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
## conditional statements in array
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [56]:
arr = np.arange(0,10)

In [57]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr / arr

C:\Users\ry363\AppData\Local\Temp/ipykernel_6000/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [64]:
1 / arr

C:\Users\ry363\AppData\Local\Temp/ipykernel_6000/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [66]:
## returns the sin value of the array

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [67]:
## returns log value of the array

np.log(arr)

C:\Users\ry363\AppData\Local\Temp/ipykernel_6000/4073970374.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [68]:
## return square root of the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr.sum()

45

In [71]:
arr.mean()

4.5

In [72]:
arr.max()

9

In [74]:
## returns standard deviation of the array

arr.std()

2.8722813232690143

In [75]:
arr.var()

8.25

In [76]:
arr_2d = np.arange(0,25).reshape(5,5)

In [77]:
arr_2d.shape

(5, 5)

In [78]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
arr_2d.sum()

300

In [79]:
## returns the sum along teh row if (axis = 0)
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [80]:
## returns the sum along the column if (axis = 1)
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])